services:

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "15672:15672" # management UI
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - microforum-net

  backend:
    image: ${BACKEND_IMAGE:-}
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - rabbitmq
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - microforum-net

  worker:
    image: ${WORKER_IMAGE:-}
    build:
      context: .
      dockerfile: sentiment.Dockerfile
    restart: unless-stopped
    depends_on:
      - rabbitmq
    env_file:
      - .env
    networks:
      - microforum-net

volumes:
  pgdata:
  rabbitmq_data:

networks:
  microforum-net:
    driver: bridge
