"""Add created_by column to users

Revision ID: 2bab140efb0c
Revises: cc83de73b13c
Create Date: 2025-06-19 09:42:55.061108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bab140efb0c'
down_revision: Union[str, Sequence[str], None] = 'cc83de73b13c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # The following columns already exist in the comments table, so skip adding them.
    # op.add_column('comments', sa.Column('created_at', sa.DateTime(), nullable=True))
    # op.add_column('comments', sa.Column('created_by', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'comments', 'users', ['created_by'], ['id'])
    # op.drop_column('comments', 'timestamp')
    # The following columns already exist in the posts table, so skip adding them.
    # op.add_column('posts', sa.Column('created_at', sa.DateTime(), nullable=True))
    # op.add_column('posts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # op.add_column('posts', sa.Column('created_by', sa.Integer(), nullable=True))
    # op.add_column('posts', sa.Column('updated_by', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'posts', 'users', ['created_by'], ['id'])
    # op.create_foreign_key(None, 'posts', 'users', ['updated_by'], ['id'])
    # op.drop_column('posts', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'updated_by')
    op.drop_column('posts', 'created_by')
    op.drop_column('posts', 'updated_at')
    op.drop_column('posts', 'created_at')
    op.add_column('comments', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'created_by')
    op.drop_column('comments', 'created_at')
    # ### end Alembic commands ###
